spring:
  h2:
    console:
      enabled: true
      path: /test_db

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:~/Documents/Dev/Workspace/Git_repository/jpa/test_db;AUTO_SERVER=TRUE
    username: test
    password: 1234
  spring.data.generate-ddl-auto: update